---
- name: Change the hostname
  win_hostname:
    name: '{{ hostname }}'
  register: host_state

- name: Reboot VM
  win_reboot:
  when: host_state.reboot_required

- name: Wait for connection
  wait_for_connection:

- name: Manage domain membership based on state variable
  ansible.windows.win_domain_membership:
    dns_domain_name: "{{ dns_domain_name if domain_membership == 'domain' else omit }}"
    domain_admin_user: '{{ domain_admin_user }}'
    domain_admin_password: '{{ domain_admin_password }}'
    # domain_ou_path: "{{ domain_ou_path if domain_membership == 'domain' else omit }}"
    workgroup_name: "{{ workgroup_name if domain_membership == 'workgroup' else omit }}"
    state: '{{ domain_membership }}'
  register: domain_state

- name: Reboot VM
  win_reboot:
    reboot_timeout: 10
  # ignore_unreachable: true
  # ignore_errors: true
  register: 'conn'
  when:
    - domain_membership == 'domain'
    - domain_state.reboot_required
  failed_when: 'conn.rebooted is defined and conn.rebooted == false'
